FROM node:18-alpine

ENV MONGO_URI="mongodb://mongodb:27017"
ENV NODE_ENV="development"
ENV DATABASE_ENV='sql'
ENV TEST_DATABASE='test'
ENV DATABASE="dicegame"
ENV PORT="5000"
ENV SQL_URI='mysql://mysql'
ENV MYSQL_USER='root'
ENV MYSQL_PASSWORD='password'
ENV HOST='mysql'
ENV JWT_SECRET='5dd0aa20-a5c7-472c-b4aa-2d7716a5a654'

COPY server/ .

WORKDIR /server
RUN npm install
RUN npm run build
EXPOSE 5000
CMD npm run dev_sql

