
version: '3.8'

x-backend_common: &backend_common
  build:
    dockerfile: Dockerfile_backend
  ports:
    - "5000:5000"
  environment:
    - MONGO_URI=mongodb://mongodb:27017
    - SQL_URI=mysql://mysql
    - HOST=mysql
  networks:
    - mafalda

services:
  backend_mongo:
    <<: *backend_common
    profiles: ["mongo"]
    container_name: backend_mongo
    command: npm run prod_mongo
    
  backend_sql:
    <<: *backend_common
    profiles: ["sql"]
    container_name: backend_sql
    command: npm run prod_sql
    
  frontend:
    build:
      dockerfile: Dockerfile_frontend
    container_name: frontend
    command: "npm run dev"
    ports:
      - "8000:5173"
 
    networks:
      - mafalda

  mongodb:
    image: mongo:6-jammy
    profiles: ["mongo"]
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - mafalda

  mysql:
    image: mysql:8.0
    profiles: ["sql"]
    environment:
      #MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mafalda


volumes:
  my-db:
  dbdata6:

networks:
  mafalda:
    driver: bridge

 