FROM node:18-alpine

ENV MONGO_URI="mongodb://mongodb:27017"
ENV NODE_ENV="development"
ENV DATABASE_ENV='sql'
ENV TEST_DATABASE='test'
ENV DATABASE="dicegame"
ENV PORT="5002"
ENV SQL_URI='mysql://mysql'
ENV MYSQL_USER='root'
ENV MYSQL_PASSWORD='password'
ENV HOST='mysql'
ENV JWT_SECRET="5dd0aa20-a5c7-472c-b4aa-2d7716a5a654"
WORKDIR /server
COPY server/package*.json .
RUN npm install
COPY server/ .
RUN npm run build
EXPOSE 5002
CMD npm run prod_sql